name = "lunatv"
compatibility_date = "2024-09-23"
# 仅当你本地需要 Node 兼容层时打开（可留着不改）
compatibility_flags = ["nodejs_compat"]

# next-on-pages 会产出到 .vercel/output
pages_build_output_dir = ".vercel/output/static"